My posted job
TaillessSheep/COMP353MainProject pull request #36
Opened 2020-08-06 13:11 UTC by zengni2018

created employer published jobs page;
can see the posted jobs,also can choose jobs by id.

2020-08-06 15:43 UTC, AxelBogos requested changes

2020-08-06 15:43 UTC, AxelBog commented on .gitignore
> +.idea/dataSources/952722df-8d9a-420e-b7c2-b7305554fb8f/storage_v2/_src_/schema/information_schema.FNRwLQ.meta
Please remove this file from the commit

2020-08-06 15:43 UTC, AxelBog commented on mypostedjob.php
> +<?php
Please remove this file from the commit

2020-08-06 15:43 UTC, AxelBog commented on employer_published_jobs.php
> +<?php require 'user_dashboard_navbar.php' //nav bar
Change to employer_dashboard_navbar

2020-08-06 15:43 UTC, AxelBog commented on employer_published_jobs.php
> +</tr>
Remove this table row for now

2020-08-07 00:16 UTC, zengni2018 commented on employer_published_jobs.php
> +<?php require 'user_dashboard_navbar.php' //nav bar
done

2020-08-07 00:18 UTC, zengni2018 commented on mypostedjob.php
> +<?php
done

2020-08-07 00:19 UTC, zengni2018 commented on .gitignore
> +.idea/dataSources/952722df-8d9a-420e-b7c2-b7305554fb8f/storage_v2/_src_/schema/information_schema.FNRwLQ.meta
done

2020-08-07 00:20 UTC, zengni2018 commented on employer_published_jobs.php
> +</tr>
done

2020-08-07 00:40 UTC, merged